### ISSUE TITLE
spyurk.am diaspora node is not listed

### ISSUE THREAD

**Issue by norayr** [thefederationinfo/the-federation.info#100]
i cannot find it here https://the-federation.info/nodes

what shell we do to be counted? (:

**Comment by norayr** [comment]
ah, adding it by https://the-federation.info/register/spyurk.am

**Comment by norayr** [comment]
looks like the pod does not appear on the list. i have

```
    ## Statistics
    ## Your pod will report its name, software version and whether
    ## or not registrations are open via /statistics.json.
    ## Uncomment the options below to enable more statistics.
    statistics: ## Section

      ## Local user total and 6 month active counts.
      user_counts: false

      ## Local post total count.
      post_counts: false
      comment_counts: false
```

still , the page works https://spyurk.am/statistics

shell i enable more statistics? it makes my node very slow.

**Comment by Flaburgan** [comment]
You don't need to enable anything the `/statistics.json` route is always available. I don't know, maybe the utf-8 support is broken. Btw, you should upgrade your pod, 0.6.4 will be released this monday ;)

**Comment by norayr** [comment]
>I don't know, maybe the utf-8 support is broken. 

can you somehow debug what's going on, and why i am unable to add the pod?

>Btw, you should upgrade your pod, 0.6.4 will be released this monday ;)

thank you, i guess i will be able to upgrade from 0.6.0.1 to 0.6.4 without intermediate releases. (:

**Comment by norayr** [comment]
or can you add the pod manually?

**Comment by Flaburgan** [comment]
>thank you, i guess i will be able to upgrade from 0.6.0.1 to 0.6.4 without intermediate releases. (:

Yes

>can you somehow debug what's going on, and why i am unable to add the pod?

@jaywink has access to the log.

**Comment by jaywink** [comment]
@norayr it looks like a character encoding problem indeed, probably in the database, will check. It is inserted though, but shown as ??????* - see here: https://the-federation.info/node/spyurk.am

Btw @Flaburgan we should not render the node graph if the node has chosen to turn off statistics - otherwise it looks weird, and also goes against the podmin choice. I'll file a separate issue.

**Comment by jaywink** [comment]
Yeah, it's the database, need to convert to charset, been stupid when setting it up. Will try to do it soon, that will fix the name then 👍 Thanks for noticing!

**Comment by jaywink** [comment]
Character encoding problem was fixed with the rewrite, closing.
