### ISSUE TITLE
Support listing of Mastodon instances

### ISSUE THREAD

**Issue by yookoala** [thefederationinfo/the-federation.info#103]
Given Mastodon instances can be federated with GNU Social, Friendica instances (haven't tried Hubzilla. could probably work too), I propose to also list / support registration of mastodon instances here.

**Comment by Flaburgan** [comment]
This website is only about projects implementing "The Federation" = the diaspora protocol at the moment. I'm completely open to add a "Fediverse" section, but until the projects can talk, I guess it should be kept separated.

**Comment by jaywink** [comment]
Personally I would love the-federation.info to contain any federated social networks. We could provide information on what federates and how and provide protocol specific statistics. Not all will ever federate. Currently yes it is based on Diaspora protocol, but I don't want to keep it that way.

A kind of blocker however is that I don't think there is a great way to pull out statistics out of Mastodon nodes. I raised this [as an issue](https://github.com/tootsuite/mastodon/issues/874) in the Mastodon issue tracker. If proper statistics were added then it would be trivial to add Mastodon support for our crawler. If none appears, I could try to have a look at how instances.mastodon.xyz does it, if it is open source (no info on the site). Any help is welcome here.

**Comment by jaywink** [comment]
Also related #66

**Comment by jaywink** [comment]
Mostly done, missing some parsing of Mastodon html for signups status, and also need to figure out how to represent statuses, since currently they are as "posts" or "comments" in the site. And in microblogging world, there are no comments, just statuses.

**Comment by jaywink** [comment]
Signups status parsing was now added, so closing this.
