### ISSUE TITLE
Create an organisation for the-federation

### ISSUE THREAD

**Issue by Zauberstuhl** [thefederationinfo/the-federation.info#121]
Since this project becomes more and more involved in our federated world it seams like a good idea to do that as a official organization rather then a private person.

**Comment by jaywink** [comment]
Done, and repo moved, thanks for the suggestion 👍 Will post out something about this.

**Comment by Flaburgan** [comment]
Wouldn't just "the-federation" be better? If we want to have more projects about this protocol :)

**Comment by jaywink** [comment]
Taken :(

**Comment by jaywink** [comment]
@Flaburgan want to join in? ;)

**Comment by Flaburgan** [comment]
Hm, 0 repositories, 0 contributions... I think if we contact github asking for it they would agree. `thefederation` without the `-` seems free, otherwise.

And yeah sure, be part of it sounds exciting!

**Comment by jaywink** [comment]
@Flaburgan that is taken too :( You need to click "Create organization" to actually be sure if something is free since some might be private, reserved due to renamed, etc.
