### ISSUE TITLE
Purge/clean-up ganggo database statistics

### ISSUE THREAD

**Issue by Zauberstuhl** [thefederationinfo/the-federation.info#122]
Cause GangGo reported a lot of false data I guess we can purge the stats and give the-federation a chance of producing correct graphs ;)

related to https://github.com/ganggo/ganggo/commit/04d0dad21869244e6197898dd367719c2a8081ae

**Comment by jaywink** [comment]
Cleaned up the local posts wrong values from first days 👍 

Ps. GangGo still has an amazing 100% user activity! ;) I will keep this open, let me know when a fix has been deployed and I can tweak the data to match current values so it doesn't look like a huge drop happened.

**Comment by Zauberstuhl** [comment]
mh I actually deployed it right away... anyway now it displays the right number!

https://ggg.social/nodeinfo/2.0
https://the-federation.info/ganggo

**Comment by jaywink** [comment]
Data cleaned, here and there, ganggo and everywhere! (well not quite, but some)
