### ISSUE TITLE
Show protocol badges on instance list

### ISSUE THREAD

**Issue by DeadSuperHero** [thefederationinfo/the-federation.info#123]
I'm not really sure how this could currently be done (as in, I'm not sure whether we currently report whether specific protocol plugins are enabled anyway), but it might be nice to represent platforms and instances that speak multiple protocols. 

For example, a Friendica instance might be compatible with Diaspora networks, ActivityPub networks, and OStatus Networks all at the same time. It would be nice to report that so users can decide whether they want to engage with these other networks when signing up.

**Comment by jaywink** [comment]
I guess it could be like the service list, initially? PR's welcome! :) We don't currently collect the protocol information, but it is available in the nodeinfo documents, so we can start collecting it, just needs a little expansion to the `pods` table schema.

In the long run I would like this site to actually show stats and nodes "per protocol", but that requires a bit more design work - and of course actually querying data from non-diaspora protocol servers.
