### ISSUE TITLE
DB  issue? 

### ISSUE THREAD

**Issue by zotlabs** [thefederationinfo/the-federation.info#124]
I don't see any recent checkins that should affect the overall stats (just the recent addition of GangGo code) but the entire federation is now listed as 9 nodes and it has been falling for a few days; starting roughly when the repository was relocated. Might want to take a look, unless I missed a shutdown notice someplace.

**Comment by jaywink** [comment]
Recent deployment (that was done for GangGo links) broke the scheduler (something to do with node), I've been copying prev day stats over for a few days manually since I've been bogged down at work too much to investigate. Will fix today, thanks for logging 👍

**Comment by jaywink** [comment]
Fix looks to be working, so closing this. Problem was in fact a bit more simple - one particular server didn't have `metadata.nodeName` in the NodeInfo 1.0 document which crashed the parsing - and crashed the whole app. Made a bit more robust.
