### ISSUE TITLE
Statistics.json turned off on Hubzilla

### ISSUE THREAD

**Issue by ghost** [thefederationinfo/the-federation.info#127]
Going forward, statistics.json will be disabled on hubzilla/red sites to force using nodeinfo. There are issues with the current parsing tools in this repository which appear to prevent this, so flagging these areas for work. 

1. Only the first entry is taken from the .host-meta/nodeinfo file; which has traditionally been version 1.0 on hubzilla sites. In nodeinfo 1.0 the network protocol and software were forced to be called 'redmatrix' by the specification despite the fact that the redmatrix project had already been abandoned when this spec was created. This would result in any hubzilla statistics being collected via nodeinfo1 under the 'redmatrix' network which I believe may prevent their display in the hubzilla network statistics. I've re-ordered the nodeinfo file to list version 2.0 as the first link which may or may not get around this. The correct fix would be to parse the revisions in this file and take the most recent supported version in the case of multiples. Merging redmatrix and hubzilla data into one network might also be desirable but only if somebody has motivation and time to kill - don't waste any developer time on it. 

2. It appears that metadata.nodeName is required, and hubzilla/red sites do not provide this; and clients requiring any specific metadata is forbidden by specification. A fix to the scripts was applied recently to alleviate this issue, but it apparently does not actually fix the issue and still appears to fallback to statistics.json when the nodeName is not present; though it may log something on the console rather than crash. I've added the metadata.nodeName (today) since we no longer have statistics.json to fallback on, but this is a questionable workaround. 

If the number of hubzilla servers starts plummeting dramatically over the next few weeks, I would like to ask for some feedback as to what we can further change to maintain compatibility with any other  undocumented requirements that I may have overlooked, or alert us to bugs which might exist on our side. I am aware that some older Hubzilla servers have malformed json in the .host-meta/nodeinfo file. This has been fixed and we just need these folks to upgrade; though theses sites will still have statistics.json as a fallback.

**Comment by jaywink** [comment]
Thanks for the heads up on these, will keep an eye on the counts and peek at logs a bit. The reason name is required is due to the nature of this site. This site isn't a normal client. I've made the name required to produce some kind of individuality into the node list. And tbh, even though it is not in the nodeinfo spec, I understood every platform adds it. We can relax that requirement for sure, defaulting to the hostname for example as name in the list, if nodename is not found.
