### ISSUE TITLE
Certificate not valid for www.the-federation.info 

### ISSUE THREAD

**Issue by Flaburgan** [thefederationinfo/the-federation.info#129]
So https://www.the-federation.info currently displays an error page.

**Comment by jaywink** [comment]
Hmm it seems the last time I renewed the cert I didn't include `www.`. I have an apache redirect to remove the www but of course that fails if the cert is invalid. I'll fix asap, need to remember how to remove the old cert first.. Thanks for reporting.

**Comment by jaywink** [comment]
Fixed!
