### ISSUE TITLE
Refactor diapod.net server sync to poll podupti.me

### ISSUE THREAD

**Issue by jaywink** [thefederationinfo/the-federation.info#131]
The former is out of maintenance. podupti.me has many servers that don't get registered here. Sync them automatically.

Discussion: https://jasonrobinson.me/content/1345030/finally-did-the-upgrade-of-socialhome-to-djang/

**Comment by Flaburgan** [comment]
diaspora-fr.org knows a lot of pods. Do you want me to share the list, manually or automatically?

**Comment by jaywink** [comment]
I would rather only automatically register servers from another list where someone has taken the choice to add the server to a list - or someone has done it for them. The diaspora-fr table could for example contain private pods that don't want to be listed but want to federate.

**Comment by Flaburgan** [comment]
Well, as anyone can currently register them manually, I don't see a big difference. Even if I agree that this always seemed a bit weird to me.

**Comment by bkil** [comment]
The same question came to mind about the general policy of this project. Why not aggregate all available lists by creating a new column that shows whether the instance was added by its owner or if it would like to stay private (and then it would only show up on aggregate statistics)?

If a server federates, a huge number of other servers will already know about that one and may just as well decide to publish their own federation lists. This could be valuable as a form of web of trust to filter out shady instances - i.e., instances which are not being blocked by a given number of trusted other instances would be trusted a bit more when dealing with blocking spam waves and DDoS. (By the way, it would be nice to see following/followed by counts per instance as well where available)

A server should be protected on multiple levels - disable registration and hide the web client & client API endpoint using a site VPN, firewalls or authorization dashboards for example. Security through obscurity is usually not a good strategy - malicious actors could probably run a worldwide query for vulnerable instances based on headers or page content using preexisting crawler databases.

> Well, as anyone can currently register them manually, I don't see a big difference. Even if I agree that this always seemed a bit weird to me.
