### ISSUE TITLE
Add protocols list to each node page

### ISSUE THREAD

**Issue by elvecio** [thefederationinfo/the-federation.info#135]
Please add information about hubs that have federation with diaspora. 
Many people assume that all the hubs on the list are federating with  diaspora.
Suggestions: add in "services" or write a little text in the hubzilla (https://the-federation.info/hubzilla) page about the possibility of finding this information in /siteinfo/json in every hubzilla hub.
Thank you.

**Comment by jaywink** [comment]
The idea is to actually provide automated network graphs and show which nodes are connected to which networks based on the protocols they provide. For platforms like hubzilla this can be very varied. The site is not meant to any more be just "this is the diaspora protocol network" so I don't want to add any diaspora specific information. 

As you suggested, lets add a `Protocols` detail to each node page, for example https://the-federation.info/node/start.hubzilla.org would give details on what protocols this particular node supports (not just for hubzilla nodes). But also separately, the graphical browser to show a network map will be added as well.

Also I have an idea of calculation a "reach" score for the node list. This would be some kind of value of total amount of users the node can reach + services modifier, so in other words, how good is the reach out from the node to the rest of the fediverse.

Thanks for the feedback!

**Comment by jaywink** [comment]
Hey @Mikaela. Currently, unfortunately, the `host` is a unique key so registering a domain name both as for example Diaspora and XMPP is not possible. I'll naturally have to change that, because now that both Matrix and XMPP have started to be registered, they often run on the same domain name as some other service. This isn't the case with the more social network type platforms.

Anyhow, I think #168 is the real issue, will comment there as well. Thanks for pointing this out.

> I am also wondering how come there is only 1 XMPP server/user, but maybe the others haven't registered themselves or are running Diaspora* which has XMPP integration?

Diaspora could easily be registered as "XMPP" if they just add it to the `protocols` list. There is already [a related issue](https://github.com/diaspora/diaspora/issues/6211) in the diaspora tracker, I'll add a comment on it.

**Comment by jaywink** [comment]
> Diaspora could easily be registered as "XMPP" if they just add it to the protocols list. There is already a related issue in the diaspora tracker, I'll add a comment on it.

DIaspora said "nope".

**Comment by Mikaela** [comment]
Are nodes able to somehow tell manually which services they are offering? I am thinking of something like [sitemap index](https://www.sitemaps.org/protocol.html#index) listing where to find the services.

I am not sure if this belongs here or #184, but what mechanisms do XMPP nodes have to say that they are XMPP nodes, how many XMPP servers support those?

**Comment by jaywink** [comment]
It depends on which metadata "standard" you use. NodeInfo allows listing services and protocols, but [only those that it accepts](http://nodeinfo.diaspora.software/schema.html). NodeInfo2 allows listing services and protocols, and [allows unknown values](https://git.feneas.org/jaywink/nodeinfo2/blob/master/schemas/1.0/schema.json). `statistics.json`, being something that was only intended for diaspora, doesn't support listing services or protocols, and has no schema. I'll remove it as a mention on the site :) 

> I am not sure if this belongs here or #184, but what mechanisms do XMPP nodes have to say that they are XMPP nodes, how many XMPP servers support those?

To answer your question depends on if you consider the xmpp to be a "service" (ie not federated) or a "protocol" (ie federated) in the particular platform. Depending on that, it should be in one of those lists.

**Comment by jaywink** [comment]
>  I'll remove it as a mention on the site :)

Ah it was in the readme only. Removed in https://github.com/thefederationinfo/the-federation.info/commit/8a6223a9bffbd8660431b7d7f63898b4ebd1ed28
