### ISSUE TITLE
Country of server

### ISSUE THREAD

**Issue by prolibre** [thefederationinfo/the-federation.info#136]
Hi,

How is the country recovered for a hubzilla server ? 
the-federation.info indicates IT (Italy) while the server is in France ? 

example: https://hub.heraut.eu in https://the-federation.info/hubzilla

**Comment by jaywink** [comment]
Interesting. We use the [ip-api.com](http://ip-api.com/) free service to resolve the country. They are reporting it as [Italy](http://ip-api.com/#178.32.218.72). Will check whether we could use some other service if this ends up being unreliable. Thanks for reporting!

**Comment by jaywink** [comment]
Finally fixed :) Countries are now shown and the one you reported also correctly.
