### ISSUE TITLE
Suggestion: Add Nextcloud -- ActivityPub supported

### ISSUE THREAD

**Issue by sunjam** [thefederationinfo/the-federation.info#138]
I'd suggest adding Nextcloud.  It uses ActivityPub.

**Comment by jaywink** [comment]
I'm not entirely sure *how* Nextcloud uses ActivityPub though. It's not really social networking, which this site focuses on. Do you have details on how they implement it and how other sites could hook into Nextcloud AP implementation?

**Comment by sunjam** [comment]
I believe it is handled through the default [Activity App](https://github.com/nextcloud/activity).  Looks like [the API was split into three parts documented here.](https://github.com/nextcloud/activity/tree/master/docs)  Perhaps @nickvergessen could provide insight as he is a part of the Nextcloud team afaik.

**Comment by jaywink** [comment]
Hmm the Activity app doesn't look like anything related to ActivityPub. Something I did find was:

> Nextcloud implements ActivityPub to inform users about changes to their files, new calendar and so on between users on different Nextcloud servers since Nextcloud 12.

https://nextcloud.com/blog/activitypub-the-new-standard-for-decentralized-networks/

But when I tried to find more information and specific details, I didn't get very far. If for example the Nextcloud ActivityPub implementation is compatible in a way to the social networking platforms (like Mastodon, Pleroma, Hubzilla, etc), then I think it belongs here. But I've not seen any evidence that this is true.

ActivityPub is more of a framework. Two ActivityPub implementations are not automatically compatible. They are only compatible if they both agree on using the same activities, delivery and so on. I'm afraid with Nextcloud as far as I have understood the it is only between Nextcloud instances (or anyone who implements AP in the same way).

An analogy I guess is that two people having a mouth doesn't automatically mean they can understand each other - they also need to speak in the same language ;)

**Comment by nickvergessen** [comment]
Exactly, atm we just use the message format of this, and it's only for cross instance communication. You can not get all your activities in this format (yet).

**Comment by doublah** [comment]
Probably worth looking at again now Nextcloud is working on an ActivityPub-based Mastodon compatible Nextcloud Social app.
https://github.com/nextcloud/social/

**Comment by doublah** [comment]
Issue for nodeinfo support in Nextcloud Social: https://github.com/nextcloud/social/issues/183

**Comment by sunjam** [comment]
[Pull request for nodeinfo support in Nextcloud](https://github.com/nextcloud/server/pull/16231)
