### ISSUE TITLE
Suggestion: Add Misskey

### ISSUE THREAD

**Issue by syuilo** [thefederationinfo/the-federation.info#139]
Are you planning to add Misskey? Thanks in advance.

https://github.com/syuilo/misskey

**Comment by jaywink** [comment]
I am now! Thanks for raising.

Are you the developer of Misskey? Could you highlight some details on how to read metadata about each Misskey instance? Metadata should include things like instance name, version, protocols supported, and optionally activity counts. See for example the [parsers here](https://github.com/jaywink/federation/blob/master/federation/hostmeta/parsers.py). If Misskey already exposes metadata, please provide links and I will check what can be extracted. Also a public list of Misskey instances would be helpful to pull in.

Thanks!

**Comment by lostinlight** [comment]
Perhaps, [this](https://git.yt/random/fediverse-network/blob/master/lib/fd/instances/crawler.ex) or [this list](https://fediverse.network/misskey) will help.

**Comment by jaywink** [comment]
Thanks @lostinlight . I'll have a look at this at some point in the near future. Tried registering some Misskey instances but the parsing fails, need to add a custom one or tweak the existing parsers.

**Comment by finkiki** [comment]
Please add misskey @syuilo @jaywink

**Comment by hakaba-hitoyo** [comment]
`GET` https://misskey.xyz/api/v1/instance or `curl -XPOST https://misskey.xyz/api/meta` brings the meta data of the Misskey instances.

**Comment by jaywink** [comment]
Thanks @hakaba-hitoyo ! Will aim to fix Misskey on the site soon.

**Comment by jaywink** [comment]
https://the-federation.info/misskey :+1: 

Can we get activity of users via some endpoint?

**Comment by jaywink** [comment]
Closing as Misskey has been on the site for a while. Activity counts would be nice but don't seem to yet be available. Please open an issue with details on how to add those once available.
