### ISSUE TITLE
hubzilla source location changed

### ISSUE THREAD

**Issue by redmatrix** [thefederationinfo/the-federation.info#140]
I'd provide a pull request but I no longer have resources (beyond this username) on github... 

The source code location for hubzilla has changed and is now https://framagit.org/hubzilla/core

**Comment by jaywink** [comment]
Fixed, thanks for reporting!

**Comment by jaywink** [comment]
Btw, no pull requests needed for the data fixes, just let me know via issue, email or chat - there is an admin now.
