### ISSUE TITLE
Suggestion: Add Write.as

### ISSUE THREAD

**Issue by thebaer** [thefederationinfo/the-federation.info#144]
I just [launched ActivityPub support](https://writing.exchange/@write_as/100517131308480767) on Write.as, so blogs are now followable in the fediverse. It's still being rolled out to all users, but we're publishing stats and I've registered our node [on _the federation_](https://the-federation.info/node/write.as). I'm not finding the `rewrite` branch, but mind if I send a pull request?

**Comment by thebaer** [comment]
Thanks @jaywink! No worries about the readme -- here's the info:

* Description: Write.as is a simple blogging platform for getting your words out and onto the web, without anything getting in your way. It gives you privacy from the start, letting you easily publish under multiple aliases, or even without signing up at all. Once you've published, you can cross-post to silos like Twitter and Medium, or reach your followers in the fediverse via ActivityPub.
* Display name: Write.as
* Icon: ![icon](https://write.as/img/w-icon-16.png)
* Tagline: Simple, connected, and privacy-focused blogging platform
* Website: https://write.as

Otherwise I think the site is great! But I'll send feedback / PRs if I come up with anything to improve.

**Comment by jaywink** [comment]
@thebaer [done](https://the-federation.info/write.as)!
