### ISSUE TITLE
Cannot register a new node

### ISSUE THREAD

**Issue by dachinat** [thefederationinfo/the-federation.info#145]
Greetings. 

We've visited https://the-federation.info and we want to register a new node.
When we try to visit 

```
https://the-federation.info/register/<ournode.tld>
```

We're getting **Server Error (500)**

Could you explain the process of including a new node on your website?

> We're running Mastodon

**Comment by jaywink** [comment]
Hi @dachinat ! So, just to be clear, you replaced `<ournode.tld>` with your domain? For example `https://the-federation.info/register/jasonrobinson.me` if I was registering mine.

If this still brings an error, could you give your domain name here (or [send it to me](https://jasonrobinson.me/content/1/contact-httpsjasonrobinsonmemediamar/)) so I can check the logs.

**Comment by dachinat** [comment]
@jaywink Hey, thanks for taking a look.

A node name is `toot.ge`

Would be great if you could take a look at the problem. Thanks!

**Comment by jaywink** [comment]
Seems to be because your server has `"contact_account":null` in the metadata. So it's a bug in our parser, will fix :+1:

**Comment by dachinat** [comment]
@jaywink Thanks! We'll check our metadata and tyr again.

**Comment by dachinat** [comment]
It worked. Thanks!
I don't know if I should open a separate issue about it, but it shows: `Open signups: No` now. We can confirm that we do have open registrations. 
<img width="169" alt="screen shot 2018-08-24 at 12 53 51 am" src="https://user-images.githubusercontent.com/22872749/44551469-4b694f00-a738-11e8-9a4c-d6ad367faa1a.png">
Thanks again!

**Comment by jaywink** [comment]
The signups parsing has now been added: https://the-federation.info/node/toot.ge

So closing this :)
