### ISSUE TITLE
Add Matrix nodes

### ISSUE THREAD

**Issue by jaywink** [thefederationinfo/the-federation.info#146]
Add a parser for Matrix metadata to support registering Matrix instances too.

**Comment by jaywink** [comment]
Reopening.

Needs to:

* [ ] Follow SRV records for `_matrix._tcp.<host>` to resolve the real location of the server
* [ ] Use standard 8448 matrix port

**Comment by eMPee584** [comment]
This seems to be done, but the statistics relying on nodes being manually registered are not only pointless, but indeed very misleading. Out of several thousand servers, only about 60 are registered...

**Comment by freshprince** [comment]
My private homeserver is now listed on this site. I did not consent to such a listing. Is there a way to get unlisted?

**Comment by jaywink** [comment]
> My private homeserver is now listed on this site. I did not consent to such a listing. Is there a way to get unlisted?

Sure, you can contact me via Matrix at `@jaywink:federator.dev`.
