### ISSUE TITLE
Can't register GNU Social nodes

### ISSUE THREAD

**Issue by Dragnucs** [thefederationinfo/the-federation.info#147]
If I try adding nodes like gnusocial.net or quitter.no, I am redirected to the home page. The nodes are never added. Currently the stats only show 3 GNU Social nodes and a total of 17 users.

**Comment by jaywink** [comment]
Thanks for reporting. GS requires a plugin for NodeInfo to be exposed, see [this issue](https://git.gnu.io/gnu/gnu-social/issues/317). I would propose contacting the admins of those servers or some GS group to raise awareness of the plugin, then they should be addable here. There is nothing I can do here, sorry.
