### ISSUE TITLE
Add slider to pod graphs to filter graphs

### ISSUE THREAD

**Issue by jaywink** [thefederationinfo/the-federation.info#16]
Slider would be used to set a maximum from current last values for the rendering of the graph - so the graphs of small pods can be viewed properly.
##

**Comment by Flaburgan** [comment]
Said differently, the users should be able to choose the start / end date of the charts.

**Comment by jaywink** [comment]
Rickshaw has [a slider](http://code.shutterstock.com/rickshaw/examples/extensions.html) but it would require updating Rickshaw and it didn't go through without some changes. Worth maybe trying though.

**Comment by Flaburgan** [comment]
Yeah but it depends of JQuery UI :s

**Comment by jaywink** [comment]
Dependencies are a requirement in web pages unless one wants to implement everything by hand ;) If we keep Rickshaw then jQuery makes sense since it has extra functions using that. If we don't, then we just depend on whatever the other library might be using.
