### ISSUE TITLE
Double entries for nodes under /Hubzilla

### ISSUE THREAD

**Issue by sunjam** [thefederationinfo/the-federation.info#160]
fwiw [I noticed a lot of Hubzilla nodes are listed multiple times on the-federation](https://the-federation.info/hubzilla).  Is this because they have migrated to additional servers via Zot protocol, or just a mistake?

**Comment by bobcanthelpyou** [comment]
It is the same for Mastodon nodes https://the-federation.info/mastodon

The address of nodes are added differently
* lower case
* starting with https
* case sensitive
* with different domain names

e.g.:
```
https://the-federation.info/node/equestria.social
https://the-federation.info/node/https:%2F%2Fequestria.social
https://the-federation.info/node/https:%2F%2FEquestria.Social

https://the-federation.info/node/elephant-bike.herokuapp.com
https://the-federation.info/node/elephant.bike
```
