### ISSUE TITLE
Duplicated nodes

### ISSUE THREAD

**Issue by c-cesar** [thefederationinfo/the-federation.info#161]
In November 7, many Mastodon instances became duplicated, increasing number of instances, users, etc. there is a noticeable bump in the graph.

```
mastodon 	Pawoo 	2.4.0 	No 	422393 	300263 	92053 				
mastodon 	Pawoo 	2.4.0 	No 	422389 	300263 	92053 				
mastodon 	Switter 	2.3.3 	No 	174297 	174297 	72241 				
mastodon 	Switter 	2.3.3 	No 	174284 	174284 	72241 				
mastodon 	mastodon.social 	2.6.1 	No 	262796 	234966 	72035 				
mastodon 	https://mastodon.social 	2.6.1 	No 	262796 	234966 	72035 		
```

**Comment by c-cesar** [comment]
There is the same issue with Hubzilla and Friendica.
The duplications seems to be because at thefederation/models/node.py host is set as unique, but using a CharField, instead of a URLField. As CharField is case sensitive, and URLs ae not, we have this node listed three times:
https://the-federation.info/node/meld.de
https://the-federation.info/node/Meld.de
https://the-federation.info/node/MELD.de

But most of nodes are duplicated because they are registered as node.tld and https://node.tld. But the last returns a 404 when we try to open the node info page.
https://the-federation.info/node/libranet.de (works)
https://the-federation.info/node/https:%2F%2Flibranet.de (404 not found)

I think some semi manual database cleaning will be necessary.

**Comment by jaywink** [comment]
Update: some cleaning done on the case/protocol dupes. Need to still clean-on-save the hostnames to avoid this problem coming up again. Will keep this open until then.

**Comment by jaywink** [comment]
Duplicates are now caught on save by doing some basic hostname cleaning and removing the protocol part. Also there is a daily job to process data that gets through and validation is improved later.

Please let me know if there are clear dupes on the lists and lets see what we can do to identify those.

**Comment by c-cesar** [comment]
Congratulations.
I think all dupes are gone now.
