### ISSUE TITLE
Add Wordpress ActivityPub plugins - Pterotype and Wordpress-ActivityPub

### ISSUE THREAD

**Issue by sunjam** [thefederationinfo/the-federation.info#163]
Hi, please consider adding these two Wordpress ActivityPub plugins.  Both allow a wordpress blog to have a federated ActivityPub stream.

* [Pterotype Plugin](https://github.com/pterotype-project/pterotype)
* [Wordpress-ActivityPub](https://github.com/pfefferle/wordpress-activitypub)

**Comment by jaywink** [comment]
Thanks for logging - will try to do this soon. Will need to look at them whether they expose any structured metadata. I'd rather not write much custom parsers to work on HTML.

All new projects I suggest adopt https://git.feneas.org/jaywink/nodeinfo2

**Comment by pfefferle** [comment]
I think it should be enough to add WordPress as a project: https://the-federation.info/#projects

**Comment by jaywink** [comment]
> Is it possible to list which specific activitypub plugin a wordpress node is running?

Would be cool imho for different plugins to expose a different name in the NodeInfo software name. Different plugins will likely have different features.

Thanks @pfefferle for the plugin!

**Comment by sunjam** [comment]
Thanks, closing here as both plugins can be listed on the-federation via the same nodeinfo2 plugin mentioned above.  Perhaps it will one day be extended to differentiate between the different activitypub plugins.  Cheers!
