### ISSUE TITLE
It is possible to register nodes with a tailing dot

### ISSUE THREAD

**Issue by ghost** [thefederationinfo/the-federation.info#167]
Could happen when copy&paste the register url with dot from the front page.
```
https://the-federation.info/node/social.bau-ha.us.
https://the-federation.info/node/toot.ordinarius-fectum.net.
```
That might lead to duplicates, again.

**Comment by jaywink** [comment]
Thanks for reporting, will improve the cleaning.

**Comment by bobcanthelpyou** [comment]
Reports of trailing dot in URI: #219
