### ISSUE TITLE
Remove invalide nodes

### ISSUE THREAD

**Issue by ghost** [thefederationinfo/the-federation.info#173]
There are a lot of instances which are no longer available cause of different issues
* ssl certificate issues (certificate verify failed)
* just redirects (to different nodes or somewhere else)
* dns issues (No address associated with hostname)
* other reachable issues (No route to host, Network is unreachable, ..)
* ...

When are those nodes be removed or hidden from the page? Maybe after a week/month in error state? Or is it possible to list them as 'in error state' or something similar on the page?

e.g. some Mastodon instances with different issues:
```
https://chubbybubble.life redirect to https://http.cat/404
https://mastodon.chris-latza.de/ selfsigned cert and 500 Internal Server Error
https://apoil.org/ Network is unreachable / Timeout
https://dev.mstdn-jp.site/ 502 Bad Gateway
https://dronesocial.me/ Could not resolve host
```

**Comment by bobcanthelpyou** [comment]
@jaywink if there is anything what could help with data maintenance to cleanup (hundreds of) faulty nodes please let me know.

**Comment by bobcanthelpyou** [comment]
Related #219 data maintenance topic
