### ISSUE TITLE
Node list page dies when rendering

### ISSUE THREAD

**Issue by jaywink** [thefederationinfo/the-federation.info#176]
Also Mastodon and Activitypub pages. The reason is the crappy table implementation + Vuejs. Need to refactor the nodes table ditching the old JS table and using some performant Vue module instead. Possibly paging as well might make sense.

**Comment by xuv** [comment]
@jaywink Not sure if you'd be up for this, but if we decide to move the design of the front-end to follow a pattern like the [Material UI](https://material.io/) design pattern for example, we could use something like [Vuetify](https://vuetifyjs.com) which has a series of predefined components that would suit this case: like their [Data Table](https://vuetifyjs.com/en/components/data-tables) component in this case. 

Vuetify would also ease the maintenance of the front-end with solid components that have been widely used and tested. What do you think? Would you be up for this?

**Comment by jaywink** [comment]
@xuv I would totally be up for that :+1: The current theme while nice has been there for a while and it predates the rewrite with Vue.js I did one year ago. I'd be totally happy to give you freedom to take good existing Vue components like Vuetify and reimplement things fully or partly where you see fit.

**Comment by xuv** [comment]
@Jaywink Nice. As you point out, I think the Data Table component could be the first one that brings quite some nice features to the UI. I'm a partisan of incremental changes, even with a UI :) . And it's nice to read that you are favorable to bringing Material UI in. I will try to submit a PR soon with these changes.
