### ISSUE TITLE
Many Wordpress instances missing from the-federation

### ISSUE THREAD

**Issue by sunjam** [thefederationinfo/the-federation.info#183]
There are [many more instances of Wordpress federation being indexed on fediverse.network](https://fediverse.network/wordpress) and it would be nice for those stats to show up on [the-federation](https://the-federation.info/wordpress) as well.  Thanks!

**Comment by jaywink** [comment]
I'd be happy if someone wrote a simple Python parser for the "All" list of `fediverse.network` - that could be then set up as a scheduled job to pull in servers registered there, to make the lists more unified. We already offer a GraphQL API should they want to do the same.

I'm kind of struggling with time atm, so contributions welcome!

**Comment by bobcanthelpyou** [comment]
I tried to register all the instance of `fediverse.network` but for most of them that didn't work. Mostly the request is redirected to a `500 Internal Server Error` page e.g.: `https://the-federation.info/register/frank.gronendahl.de` at least 5 instances where added.

**Comment by jaywink** [comment]
Seems to be:

```
Traceback:

...
File "/src/federation/federation/hostmeta/fetchers.py" in fetch_nodeinfo2_d=
ocument
  90.     return parse_nodeinfo2_document(doc, host)

File "/src/federation/federation/hostmeta/parsers.py" in parse_nodeinfo2_do=
cument
  232.         raise ValueError('NodeInfo2 baseUrl is outside called host.')

Exception Type: ValueError at /register/frank.gronendahl.de/
Exception Value: NodeInfo2 baseUrl is outside called host.
```

Seems to be an error with `/` at the end... Will fix.

**Comment by jaywink** [comment]
@bobcanthelpyou btw, you seem enthusiastic about helping maintain the site. Would you like admin access? It doesn't grant any additional data access, since all the data is available already via open API's, but it grants you access to maintain some information via the admin UI, for platforms, nodes and protocols. If you do, please PM me your email via [one of my contact details](https://jasonrobinson.me/content/1/contact-httpsjasonrobinsonmemediamar/).

**Comment by jaywink** [comment]
Actually after scratching my head for a while I noticed that the NodeInfo2 document presented by `frank.gronendahl.de` is wrong. It lists `baseUrl` in a `software` object when the schema defines it in a `server` object. Please see https://git.feneas.org/jaywink/nodeinfo2/blob/master/schemas/1.0/schema.json#L18

Their nodeinfo2 document is at https://frank.gronendahl.de/.well-known/x-nodeinfo2

AFAICT this is correct in the wordpress NodeInfo plugin: https://github.com/pfefferle/wordpress-nodeinfo/blob/master/includes/class-nodeinfo2.php .. So not quite sure what is wrong? Maybe they are running some old pre-release version of the plugin?

**Comment by sunjam** [comment]
@pfefferle any ideas on this?

> Actually after scratching my head for a while I noticed that the NodeInfo2 document presented by frank.gronendahl.de is wrong. It lists baseUrl in a software object when the schema defines it in a server object. Please see https://git.feneas.org/jaywink/nodeinfo2/blob/master/schemas/1.0/schema.json#L18

> Their nodeinfo2 document is at https://frank.gronendahl.de/.well-known/x-nodeinfo2

> AFAICT this is correct in the wordpress NodeInfo plugin: https://github.com/pfefferle/wordpress-nodeinfo/blob/master/includes/class-nodeinfo2.php .. So not quite sure what is wrong? Maybe they are running some old pre-release version of the plugin?

**Comment by pfefferle** [comment]
Oh! I implemented a basic nodeinfo version in my ActivityPub plugin! I think there is the problem! @sunjam can you file an issue here https://github.com/pfefferle/wordpress-activitypub ? I will fix it ASAP!

**Comment by pfefferle** [comment]
should be fixed now!

**Comment by pfefferle** [comment]
@sunjam @jaywink can you recheck and close the issue?

**Comment by jaywink** [comment]
The patch looks correct @pfefferle so I'm closing this - the wordpress instances not being able to list just need to update their plugin. Thanks!
