### ISSUE TITLE
What are NodeInfo, NodeInfo2, Statistics.json or Mastodon stats API endpoint?

### ISSUE THREAD

**Issue by Mikaela** [thefederationinfo/the-federation.info#184]
> How to get your platform listed
> 
> Implement NodeInfo, NodeInfo2, Statistics.json or Mastodon stats API endpoint.

This is from the README.md, but there is no further explanation or links where to learn more and especially `Statistics.json` appears to be somewhat ungoogleable.

**Comment by jaywink** [comment]
Added links.
