### ISSUE TITLE
Mastodon-API compatible software listed as Mastodon

### ISSUE THREAD

**Issue by Toromino** [thefederationinfo/the-federation.info#190]
[Kibou](https://git.cybre.club/kibouproject/kibou) is another federated social network project which supports Mastodon's REST-API. Nodes running the Kibou software were once listed as their own project on the-federation.info when it only supported nodeinfo, but after we started supporting Mastodon's ``api/v1/instance`` endpoint it is now listed under Mastodon.

Here's an example: 
![image](https://user-images.githubusercontent.com/15093096/60133862-885e0200-979e-11e9-87e3-3265554f9dbd.png)
[https://the-federation.info/node/kodachrome.club](https://the-federation.info/node/kodachrome.club)

**Comment by jaywink** [comment]
Hi, thanks for reporting. That is annoying. The only reason we scrape Mastodon API is that they don't offer a more standard document to scrape.

I suppose the only way to fix this is to in addition to Mastodon API start also scraping NodeInfo docs and then merge the information from those. It wouldn't be a huge development effort, but unfortunately my time is very limited currently. Patches are welcome should anyone want to help! The part where things happens are https://github.com/thefederationinfo/the-federation.info/blob/master/thefederation/tasks.py#L146 and https://github.com/thefederationinfo/the-federation.info/blob/master/thefederation/tasks.py#L92 - which need some restructuring.

**Comment by jaywink** [comment]
This is now fixed for Kibou and a few other platforms.
