### ISSUE TITLE
Suggestion: Rocket.chat

### ISSUE THREAD

**Issue by sunjam** [thefederationinfo/the-federation.info#191]
Please consider adding [Rocket.chat](https://github.com/RocketChat/Rocket.Chat), a drop-in FOSS Slack replacement, as instances can federate with each other for several releases now.

**Comment by jaywink** [comment]
Interesting, didn't know that. [Reference in docs](https://rocket.chat/docs/user-guides/talking-to-users-from-another-server/).

Would be happy to list Rocket.chat instances if either they implement [NodeInfo2](https://git.feneas.org/jaywink/nodeinfo2) (the Diaspora NodeInfo wont be compatible in this case) for federated servers, or if someone contributes a parser for some Rocket.chat specific server metadata that is exposed from federated servers. The parser should be contributed preferably to the [federation library](https://git.feneas.org/jaywink/federation/blob/master/federation/hostmeta/parsers.py) where all the other parsers used live.

Thanks for raising!

**Comment by 6543** [comment]
upstream issue was closed.

they will also join via matrix protocol ... so by #287  it is covered ...
