### ISSUE TITLE
Suggestion: add Movim (XMPP based)

### ISSUE THREAD

**Issue by ashledombos** [thefederationinfo/the-federation.info#195]
Hello,

I'd like to suggest a tool based on XMPP called Movim.

* URL to code
https://github.com/movim

* Description
Movim is a set of software (web platform, desktop/mobile clients) which relies on XMPP.
 It allows to do social networking (with reshare, public/private publishing…), micro/macroblogging (with comments, likes etc) and communications (message correction, reactions, received message notification, "…is writing" notification, stickers, one-to-one or group, document sharing, audio-visio conference,…) . Of course it's federated.

* Display name
Movim

* Code license
AGPLv3 license

* Icon
https://movim.eu/img/vectorial.svg

* URL to install guide
General instruction: https://github.com/movim/movim/wiki
With docker: https://github.com/movim/movim_docker
Debian package: https://packages.debian.org/sid/movim/

* Tagline
The social platform shaped for your community
…and that federates with the others

Don't reinvent the wheel.

* URL to official website
https://movim.eu

**Comment by jaywink** [comment]
Hi @ashledombos !

Thanks for logging. For sure Movim (and other XMPP based federated platforms) is welcome on the lists. However we don't maintain data manually. All the data is scraped from the sites themselves. For Movim instances to appear on the site, please see [these instructions](https://github.com/thefederationinfo/the-federation.info#how-to-get-your-platform-listed). In short, Movim needs to implement some metadata that allows us to get information about the servers.

There is also a new metadata specification I'm working on which I would be happy to get comments about called ServerInfo, please see https://talk.feneas.org/t/serverinfo-specification-for-server-metadata/99 .. I plan to write a parser for it for this site very soon.

Alternatively if Movim already exposes metadata about servers, you're welcome to contribute a parser to the [federation library we use](https://git.feneas.org/jaywink/federation/blob/master/federation/hostmeta/parsers.py).

I'll keep this issue open until one of those things happen. Then things will just work.

**Comment by ashledombos** [comment]
Thank you @jaywink, I come back on this issue soon after I join the dev team :)

**Comment by stragu** [comment]
Just FYI, the main developer is reluctant to implement anything until there is something "stable and fully specified": https://github.com/movim/movim/issues/909#issuecomment-602206951
