### ISSUE TITLE
Main /nodes list is broken due to 404 on /graphql

### ISSUE THREAD

**Issue by jaywink** [thefederationinfo/the-federation.info#197]
It's not a real 404 but something timeouting and nginx giving what looks like a 404. This is probably due to the bad way the app is deployed and the bad way the GraqlQL queries access the database.

The error in backend stdout is: `[2019-10-01 15:47:00 +0000] [38] [CRITICAL] WORKER TIMEOUT (pid:43)`

**Comment by dmorley** [comment]
this also breaks the poduptime crawl :( any other way to this data?

**Comment by jaywink** [comment]
> this also breaks the poduptime crawl :( any other way to this data?

I hope you don't scrape the HTML? There is a GraphQL API available which does not timeout, unless you build a monster query, like the frontend does :grimacing: 

For example getting a list of [nodes by name](https://the-federation.info/graphql#query=query%20%7B%0A%20%20nodes%20%7B%0A%20%20%20%20host%0A%20%20%7D%0A%7D).

I might just rewrite the API with a simple REST thingy since GraphQL was clearly a mistake for this kind of data which is mainly not a graph. But it could take a bit. So I'd recommend using the GraphQL endpoint for now.

Also there is the [legacy pods.json](https://the-federation.info/pods.json) maintained for legacy purposes - maybe that is simpler?

**Comment by dmorley** [comment]
Ah, I have been using:

https://the-federation.info/graphql?query=%7Bnodes%7Bhost%20platform%7Bname%7Dprotocols%7Bname%7D%7D%7D&raw

For a while. It looks like if I remove the protocols part it is happy. Can't seem to use &raw however, wonder how I did that before to get a good json
