### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by WonderingDane** [thefederationinfo/the-federation.info#199]
When trying to add `https://the-federation.info/register/pixelfed.dk/` I get a server error 500.

Please advise.

**Comment by jaywink** [comment]
Looks like `pixelfed.dk` defines organization contact as `null` and my federation library tries to respect it too strictly, causing things to fail as empty charfields should be set (to the default) `''`, not null.

```
IntegrityError at /register/pixelfed.dk/ null value in column "organization_contact" violates not-null constraint
```

What is interesting is that the whole site is being recognized as `Mastodon`, not `Pixelfed`. Has Pixelfed implemented the Mastodon API? That would be annoying as there we would have to then move polling the Mastodon API to the last in line, to avoid NodeInfo exposing platforms being identified as Mastodon :(

**Comment by WonderingDane** [comment]
Maybe @dansup know what is going on?

I'm not sure how I should be defining "organization contact"?

**Comment by timboswell** [comment]
I'm seeing the same behaviour on pixelfed.uk - is this the same error in the backend? Where is organization_contact defined?

**Comment by WonderingDane** [comment]
Anything new here? Still can't add pixelfed.dk as an instance and I have no idea where I define "organization_contact".

**Comment by jaywink** [comment]
(note fix not deployed yet, will do so in a few, will shout here if it worked :D)

**Comment by jaywink** [comment]
Seems to work:
https://the-federation.info/node/pixelfed.dk
https://the-federation.info/node/pixelfed.uk

Sorry the fix took such a long time. And it wasn't in PixelFed.

**Comment by WonderingDane** [comment]
> Seems to work:
> https://the-federation.info/node/pixelfed.dk
> https://the-federation.info/node/pixelfed.uk
> 
> Sorry the fix took such a long time. And it wasn't in PixelFed.

Thank you very much, @jaywink :D

**Comment by WonderingDane** [comment]
How do I add "country"?

**Comment by jaywink** [comment]
> How do I add "country"?

That was a bug the country not showing. It shows now :)
