### ISSUE TITLE
Suggestion: Lemmy

### ISSUE THREAD

**Issue by sunjam** [thefederationinfo/the-federation.info#208]
[Lemmy](https://dev.lemmy.ml/) is federated Reddit clone, which [recently added nodeinfo support](https://github.com/dessalines/lemmy/issues/144#issuecomment-489304621)  in [this pull request](https://github.com/dessalines/lemmy/commit/9c94e23fcd98e04eecf69611864ddb39d235664b)

**Comment by jaywink** [comment]
Their main instance NodeInfo looks broken: https://dev.lemmy.ml/.well-known/nodeinfo

**Comment by Nutomic** [comment]
The dev instance is fixed now. Also fyi, Lemmy is not federated yet, but it will support ActivityPub in the future.

**Comment by jaywink** [comment]
Works now, thanks @Nutomic \o/ 

https://the-federation.info/lemmy
