### ISSUE TITLE
Add Prosody software

### ISSUE THREAD

**Issue by linkmauve** [thefederationinfo/the-federation.info#209]
- URL to code: https://hg.prosody.im/trunk
- Description: Lightweight XMPP server written in Lua.
- Display name: Prosody
- Code license: MIT
- Icon: https://prosody.im/prosody.svg
- URL to install guide: https://prosody.im/download/start
- Tagline: A study in simplicity.
- URL to official website: https://prosody.im/

This community module provides the nodeinfo2 file: https://modules.prosody.im/mod_nodeinfo2.html

I already added four services I run using this software, which you can see here: https://the-federation.info/prosody

**Comment by jaywink** [comment]
I've added the info, thanks!

If you have a list of Prosody instances somewhere, feel free to paste here at some point and I can mass-read them in.

**Comment by linkmauve** [comment]
Prosody doesn’t ship mod_nodeinfo2 by default (yet?), but I have some idea to expand the list of nodes despite that, highlighted in #211.

**Comment by linkmauve** [comment]
Here is a list of other servers I administrate: https://linkmauve.fr/files/jabberfr-hostnames.txt

**Comment by jaywink** [comment]
> Any idea why e.g. https://the-federation.info/node/jabber.fr only displays an error in the console btw?

Trying to render things before they were fetched from the backend, fixed now, thanks for spotting.

> And finally, how do you determine the country? It doesn’t seem to pick that all four nodes I added are in France, but I couldn’t find any information in the nodeinfo2 schema about where to specify it.

It's determined based on IP from the [Maxmind](https://dev.maxmind.com/geoip/geoip2/geolite2/) database. Are there some that are not correct?

> Here is a list of other servers I administrate: https://linkmauve.fr/files/jabberfr-hostnames.txt

I triggered a fetch for all these but no new ones got added. Do they run the nodeinfo2 module?

**Comment by linkmauve** [comment]
> It's determined based on IP from the [Maxmind](https://dev.maxmind.com/geoip/geoip2/geolite2/) database. Are there some that are not correct?

None anymore, they just didn’t have any country set but that’s been fixed since then. Probably the time to fetch them all.

> > Here is a list of other servers I administrate: https://linkmauve.fr/files/jabberfr-hostnames.txt
>
> I triggered a fetch for all these but no new ones got added. Do they run the nodeinfo2 module?

They all do, but I just fixed a certificate issue which was probably the issue!
