### ISSUE TITLE
Let servers expose other servers they directly federate with

### ISSUE THREAD

**Issue by linkmauve** [thefederationinfo/the-federation.info#211]
This could be used to expend the federation very easily. A given server would say which other servers it is currently federating with, and all of them would get a shadow profile on the website until they are scrapped. If they don’t provide a nodeinfo2 file yet, they could at least be discovered and counted towards the nodes count.

https://github.com/ThomasLeister/mod_serverinfo was a previous attempt at this same feature, it was used to display a very neat graph view of the interconnections between servers (see https://youtu.be/xNXx0wtjSy0 for instance), I’d love to see that effort resurrected at some point!

**Comment by Ppjet6** [comment]
While I would love to see a feature like this, there might be servers that don't really want to be scraped and displayed publicly. Would there be a way to have an opt-in mechanism while still gathering server-to-server numbers maybe?

**Comment by ThomasLeister** [comment]
Hmm I understand that some server might not want to be listed publicly (or don't want to offer and information about connectivity)...
Maybe it would be a solution to only show a node's name if the owner opted in before (and show anonymous node names if he/she didn't.)

An easier solution would be to just show nodes _by their name_ if they are running the "information" server module themselves and leave all the rest anonymous. 

All in all I'd rather like to see all the server names, but I see why this could lead to a controversy.

**Comment by Ppjet6** [comment]
What about gathering hashes of servers we're currently federating with? The goal would be to make it just slightly expensive to scan the whole internet.

HostA federates with HostB and HostC. HostA includes a list of federated hosts:
- hash(HostB)
- hash(HostC)

HostD federates with HostB. HostD includes a list a federated hosts:
- hash(HostB)

Thefederation is able to decloack/deduplicate HostB (even if the node isn't registered) and count it only once.

HostB registers, and is now competely decloacked and federation status with HostA and HostD is made public. (Whether this information is published in the interface is another matter).

The hash function used could be pbkdf2, scrypt, etc..

A salt is not really necessary, but in case you'd want to use one, `yyyy-MM` could be used (thefederation probably stores the last updated timestamp?)

Does this sound sane? If so, where should we add this information?

**Comment by jaywink** [comment]
> This could be used to expend the federation very easily. A given server would say which other servers it is currently federating with, and all of them would get a shadow profile on the website until they are scrapped. If they don’t provide a nodeinfo2 file yet, they could at least be discovered and counted towards the nodes count.

I think it would be a great idea to use this kind of information from the host documents, whether nodeinfo(2) or some other format. But I would not count the instances or especially show them in the UI until they present some kind of proof that they are really there. They could be added into the database for regular polling but probably on a less tight schedule, otherwise it would open a nasty way of taking down the site by exposing a nodeinfo document listing 1 million random domain names which would clog the site polling ;)

To get listed and to have regular pollings happen IMHO there needs to be a successful fetch first.

**Comment by Ppjet6** [comment]
> But I would not count the instances [..] until they present some kind of proof that they are really there.

That somewhat defeats the point of this feature to me. I think in the same way you trust hosts to give you a message count (it count be totally arbitrary), you could very well trust them to disclose a list of connections they have.

**Comment by Ppjet6** [comment]
Maybe a way to do this could be to have registered nodes provide an encrypted list of hosts they federate with, so that the data is not actually public, and you can use it. This might get quite expensive to generate/read though on both sides.

**Comment by bkil** [comment]
Related to [#131](https://github.com/thefederationinfo/the-federation.info/issues/131#issuecomment-1013958844)
