### ISSUE TITLE
Remove Duplicate Nodes

### ISSUE THREAD

**Issue by ghost** [thefederationinfo/the-federation.info#219]
Remove duplicate nodes, e.g. 
- https://the-federation.info/node/social.bau-ha.us.
- https://the-federation.info/node/social.bau-ha.us

(note the trailing dot in URI). 
There are others as well listed under Mastodon and maybe needs more checking: 
- https://the-federation.info/node/artalley.porn vs. https://the-federation.info/node/artalley.social
- https://the-federation.info/node/b612.icu vs https://the-federation.info/node/b612.me
- https://the-federation.info/node/cocoronavi.com vs https://the-federation.info/node/cocoronavi.net
- maybe: https://the-federation.info/node/cyb3r.social vs https://the-federation.info/node/cyber.social
- https://the-federation.info/node/elephant-bike.herokuapp.com vs https://the-federation.info/node/elephant.bike
- https://the-federation.info/node/imastodon.net vs https://the-federation.info/node/imastodon.org
- maybe: https://the-federation.info/node/mckellar.org vs https://the-federation.info/node/mckellar.social
- https://the-federation.info/node/pawoo.net vs https://the-federation.info/node/pawoo.noellabo.jp (apparently just the display name)
- https://the-federation.info/node/tebukuro.pw vs https://the-federation.info/node/tebukuro.xyz
- maybe: https://the-federation.info/node/tegedon.net vs https://the-federation.info/node/test.tegedon.net
- https://the-federation.info/node/toot.ordinarius-fectum.net. vs https://the-federation.info/node/toot.ordinarius-fectum.net
- https://the-federation.info/node/unkomaker.info vs https://the-federation.info/node/unkomaker.net

This is just a list of visual check based on the listed names of the Mastodon instances. Apparently it needs deeper checking and most likely there will some duplicates for other projects as well.

**Comment by c-cesar** [comment]
After digging a little on the list, this is a lot of different issues.

1. Tailing dot
social.bau-ha.us. vs social.bau-ha.us

1. Persistence of old/inactive instances
artalley.porn (dead) vs. artalley.social (alive)

1. Mastodon nodeinfo on unknown software
b612.icu (mastodon) vs b612.me (unknown. Seems to e a blog)

1. URL redirection
cocoronavi.com redirects to -> cocoronavi.net

1. Really two instances, nothing wrong (different stats, et all)
cyb3r.social vs cyber.social

1. Same instance accessible by two URLs (This would break ActivityPub, and should be avoided by instance admins)
elephant-bike.herokuapp.com vs elephant.bike

I think only 1 and 4 are bugs and should be fixed. For 2, a good feature request would be the addition of a "online/offline" indicator, as node data are stored by quite some time.

3 and 6 are not bugs of this project.
