### ISSUE TITLE
Don't list duplicate entries

### ISSUE THREAD

**Issue by goobertron** [thefederationinfo/the-federation.info#22]
I noticed one pod is listed twice, for `https://podname.tld` and `https://www.podname.tld`

It would be good to have any such pods listed only once. I guess they perhaps registered twice, one with each variant, so if the code could catch this and tell them they're already registered, that would probably be the best solution.
##

**Comment by royalterra** [comment]
I have the seam issue and I ask how I can delete in the database possible one option is change all to www in the database and see if the cron delete one entry

**Comment by Flaburgan** [comment]
This should be fixed if we want accurate numbers, especially with #102 which could be used to take decisions about how to drive the protocol breaking changes.

**Comment by SuperTux88** [comment]
librenet.gr is also a duplicate

Side note: There are pods with the same name, but different domains: "MondiAspora*" for example is no duplicate, it's two different pods (one with .org and one with .net).

**Comment by Flaburgan** [comment]
I think we should to remove the duplicate based on the url, and modify the import code to first check if the pod is already there when a user submits it.

**Comment by jaywink** [comment]
Some of the current duplicates to work through:

```
In [17]: for node in nodes:
    ...:     ips = Node.objects.filter(name=node['name']).values_list('ip', flat=True)
    ...:     successs = Node.objects.filter(name=node['name']).values_list('last_success', flat=True)
    ...: 
    ...:     successs = {success.date() for success in successs}
    ...:     platforms = Node.objects.filter(name=node['name']).values_list('platform', flat=True)
    ...:     if len(set(ips)) == 1 and len(successs) == 1 and len(set(platforms)) == 1:
    ...:        these = Node.objects.filter(name=node['name']).values('host', 'platform__name')
    ...:        for thee in these:
    ...:            print(thee)
    ...:        print("")
    ...:        
{'host': 'pixel.inari.click', 'platform__name': 'pixelfed'}
{'host': 'inari.pics', 'platform__name': 'pixelfed'}

{'host': 'peertube.mes-courriers.fr', 'platform__name': 'peertube'}
{'host': 'pe.ertu.be', 'platform__name': 'peertube'}

{'host': 'ukadon-test.shillest.net', 'platform__name': 'mastodon'}
{'host': 'ukadon.shillest.net', 'platform__name': 'mastodon'}

{'host': 'mstdn.i-red.info', 'platform__name': 'mastodon'}
{'host': 'geotdn.i-red.info', 'platform__name': 'mastodon'}

{'host': 'ps.s10y.eu', 'platform__name': 'mastodon'}
{'host': 's10y.eu', 'platform__name': 'mastodon'}

{'host': 'mstdn.lalafell.org', 'platform__name': 'mastodon'}
{'host': 'mstdn.lalafell.org.', 'platform__name': 'mastodon'}

{'host': 'io.hfrc.de', 'platform__name': 'hubzilla'}
{'host': 'hubz.hfrc.de', 'platform__name': 'hubzilla'}
{'host': 'allnet.hfrc.de', 'platform__name': 'hubzilla'}
{'host': 'a1.hfrc.de', 'platform__name': 'hubzilla'}

{'host': 'blimps.xyz', 'platform__name': 'mastodon'}
{'host': 'www.blimps.xyz', 'platform__name': 'mastodon'}

{'host': 'moe.cat', 'platform__name': 'mastodon'}
{'host': 'm.moe.cat', 'platform__name': 'mastodon'}

{'host': 'social.gnuaspora.de', 'platform__name': 'unknown'}
{'host': 'gnuaspora.de', 'platform__name': 'unknown'}

{'host': 'mondiaspora.net', 'platform__name': 'diaspora'}
{'host': 'mondiaspora.org', 'platform__name': 'diaspora'}

{'host': 'mastodon.die-partei-reutlingen.de', 'platform__name': 'mastodon'}
{'host': 'die-partei.social', 'platform__name': 'mastodon'}

{'host': 'www.15o2.de', 'platform__name': 'friendica'}
{'host': '15o2.de', 'platform__name': 'friendica'}

{'host': 'MELD.de', 'platform__name': 'friendica'}
{'host': 'meld.de', 'platform__name': 'friendica'}

{'host': 'gs.smuglo.li', 'platform__name': 'pleroma'}
{'host': 'pl.smuglo.li', 'platform__name': 'pleroma'}

{'host': 'www.librenet.gr', 'platform__name': 'diaspora'}
{'host': 'librenet.gr', 'platform__name': 'diaspora'}

{'host': 'aria.dog', 'platform__name': 'pleroma'}
{'host': 'barks.aria.dog', 'platform__name': 'pleroma'}

{'host': 'spod.ca', 'platform__name': 'mastodon'}
{'host': 'mstdn.spod.ca', 'platform__name': 'mastodon'}

{'host': 'datataffel.dk', 'platform__name': 'diaspora'}
{'host': 'www.datataffel.dk', 'platform__name': 'diaspora'}

{'host': 'www.mstd.tokyo', 'platform__name': 'mastodon'}
{'host': 'mstd.tokyo', 'platform__name': 'mastodon'}
```

Some action points:
* check on register for duplicates based on IP, platform type and latest stat reported. If they all match -> it is for sure a duplicate. What do we do though? Do we replace the old host with the new host or just don't save the new host?
* delete current dupes
* some (already delete, not in above list) dupes were from mastodon for example `user@mastodon.social`. We should not allow hosts with `@` in them, just do an rsplit and take the last part of the split for the host.

**Comment by goobertron** [comment]
It would to technically possibly to run two nodes (we're no longer talking only about pods) on different sub-domains of the same domain, so I don't think the correct solution is just to merge any records using the same domain.

Cases where one record includes the protocol and the other doesn't – such as librenet.gr and www.librenet.gr – can definitely be merged. It used to be possible to connect to the same pod via both methods if it hadn't been set up properly, but I'm fairly sure Maxwell closed that loophole after I pointed it out.

Would it be possible to get the site to ping such nodes and see if it's redirected? E.g. 
social.gnuaspora.de and gnuaspora.de – I assume in such a case one URL would redirect to the other, correct one if they do relate to one and the same node. Or perhaps the second would return an error if it's not running a working node, just some code that for some reason is sending node-info.

Apologies if any of this is a load of technical nonsense.
