### ISSUE TITLE
Change Misskey's domain

### ISSUE THREAD

**Issue by aleksandar-todorovic** [thefederationinfo/the-federation.info#228]
Misskey changed its domain from misskey.xyz to misskey.io. The project's GitHub page appears to confirm this new location: https://github.com/syuilo/misskey

Since misskey.xyz currently appears offline, it might lead to the impression that the project is dead, which is why I believe it needs to be updated.

**Comment by ingoj** [comment]
Changed setting to misskey.io. 

Please verify and close this issue then.

**Comment by aleksandar-todorovic** [comment]
Yup, Misskey now points to the right domain. Thanks!
