### ISSUE TITLE
Add project: kepi

### ISSUE THREAD

**Issue by marnanel** [thefederationinfo/the-federation.info#233]
URL to code: https://gitlab.com/marnanel/kepi
Description: A Django microblogging server
Display name: kepi
Code license: GPLv2
Icon: ![kepi-16x16](https://user-images.githubusercontent.com/292241/94978507-74fb2400-0515-11eb-8dad-c4c75ba2f7f5.png)
URL to install guide: https://gitlab.com/marnanel/kepi/-/blob/main/docs/installation.md
Tagline: A Django microblogging server
URL to official website: https://kepi.org.uk

Thanks!

**Comment by 6543** [comment]
done
