### ISSUE TITLE
My Friendica instance miscategorized as Mastodon

### ISSUE THREAD

**Issue by PirxGR** [thefederationinfo/the-federation.info#239]
![Zrzut ekranu-20210123082432-1861x963](https://user-images.githubusercontent.com/33618992/105572085-41a70400-5d55-11eb-9f2e-e843634f908a.png)

I just submitted my site for registration and both software type and user stats are wrong. Please advise.

**Comment by jaywink** [comment]
This is basically https://github.com/thefederationinfo/the-federation.info/issues/214

Unfortunately the fix is "someone needs to fix the code". I'm open for contributors to the project, unfortunately myself I am unavailable for working on the project currently due to time constraints.
