### ISSUE TITLE
Backend code links to feneas gitlab repo for federation module

### ISSUE THREAD

**Issue by weex** [thefederationinfo/the-federation.info#263]
Per @jaywink the preferred repo for further development is https://github.com/jaywink/federation so this repo should probably pull from there.

**Comment by bkil** [comment]
Especially with the nearing deadlines of shutting their servers down:
* https://git.feneas.org/feneas/association/-/raw/master/comms/dissolving-the-association-2022-01-09.txt

**Comment by weex** [comment]
Effect unclear as the-federation.info wasn't included in that announcement

**Comment by bkil** [comment]
https://github.com/thefederationinfo/the-federation.info/search?q=feneas
