### ISSUE TITLE
Projects Using (the API of) the Website

### ISSUE THREAD

**Issue by 6543** [thefederationinfo/the-federation.info#282]
* [GreenFediverse](https://chaos.social/@greenfediverse)
* [nodes.fediverse.party](https://github.com/Minoru/minoru-fediverse-crawler) (https://github.com/thefederationinfo/the-federation.info/issues/282#issuecomment-1116376028)

**Comment by Minoru** [comment]
https://github.com/Minoru/minoru-fediverse-crawler uses GraphQL to get hostnames of all ActivityPub instances ([code](https://github.com/Minoru/minoru-fediverse-crawler/blob/449f76b2b2c2045e4b202424a7610a98384c788f/scripts/fetch_the-federation)), and also fetches "pods.json" ([code](https://github.com/Minoru/minoru-fediverse-crawler/blob/449f76b2b2c2045e4b202424a7610a98384c788f/scripts/fetch_the-federation_pods); I found this endpoint contains some AP instances not mentioned in the GraphQL API).

I'm fine with those particular APIs getting broken or removed; just give me a way to fetch all AP instances the-federation knows about.
