### ISSUE TITLE
Add numbers about up-to-date pods

### ISSUE THREAD

**Issue by Flaburgan** [thefederationinfo/the-federation.info#42]
To take decision about the evolution of the federation (as in https://github.com/SuperTux88/diaspora_federation/issues/29 for example), it would be cool to have version number (n and % of the network for the pods and the users) such as:
- How many pods are using the current stable version
- How many pods are using the previous stable version
- How many pods are using an coming develop version (doesn't include old develop)

So something like "231 pods (78%) containing 378 971 users (65%) are using the current stable version of diaspora*".
##

**Comment by Flaburgan** [comment]
As this should help to take decision about diaspora* upgrade, it's of course a % of the **diaspora** pods and users, including not Friendica & Cie.

**Comment by jaywink** [comment]
Wow, I didn't even know about such schedules. It's nice the amount of communication we have in the core team between totally breaking backwards compatibility...

**Comment by Flaburgan** [comment]
@jaywink @supertux88 posted this recently and it's only a proposition from his side, nobody reacted at the moment.

**Comment by jaywink** [comment]
Actually you can already get this data by taking [this json endpoint](https://the-federation.info/pods.json) and just running some calculations on the versions.

If anyone wants to contribute this as a nifty piece of statistics on the site, please make it general, versions per platform, not just diaspora.

**Comment by Flaburgan** [comment]
It would also be cool to add a field to tell when the pod was updated, to be able to say something like "This pod was updated 12 days after the release". A different topic though.
