### ISSUE TITLE
Add IRC and Matrix chats to site

### ISSUE THREAD

**Issue by jaywink** [thefederationinfo/the-federation.info#70]
For those who want to chat about The Federation there is an IRC channel and Matrix room which are bridged together.

Matrix: https://matrix.to/#/#thefederation:feneas.org
freenode: #thefederation

**Comment by Flaburgan** [comment]
You mean to add this indication or to include a webchat inside the website?

**Comment by jaywink** [comment]
@Flaburgan I mean just indication / links

**Comment by Flaburgan** [comment]
Hm I can add that on the "about" page if that is enough.

**Comment by jaywink** [comment]
Yes I think that would be the correct place 👍

**Comment by Mikaela** [comment]
> FreeNode: #thefederation

They used to have a FAQ saying that they are actually "freenode" and that weird capitalization comes from Xchat.

>  Telegram: https://t.me/joinchat/AAAAAArFW1VdTC9p1rPwWg

"This link is invalid or has expired." says Telegram.

**Comment by jaywink** [comment]
Updated description.
